FROM php:8.2-cli
RUN apt-get update && apt-get install -y libpq-dev unzip git
RUN docker-php-ext-install -j$(nproc) pgsql
RUN docker-php-ext-enable pgsql
# RUN pecl install --soft --force xdebug-3.2.1
# RUN docker-php-ext-enable xdebug
