version: '3.7'
services:
    postgres:
        image: postgres:14
        env_file: [docker.env]
        restart: "no"

    php80:
        image: php:8.0-cli
        depends_on: [postgres]
        build: {context: ".",  dockerfile: "./Dockerfile-8.0"}
        restart: "no"
        env_file: [docker.env]
        working_dir: /var/code
        volumes:
            - "../composer.json:/var/code/composer.json"
            - "../phpunit.xml.dist:/var/code/phpunit.xml.dist"
            - "../src:/var/code/src"
            - "../tests:/var/code/tests"
            - "./composer.phar:/var/code/composer.phar"
            - "./run-internal.sh:/var/code/run-internal.sh"

    php81:
        image: php:8.1-cli
        depends_on: [postgres]
        build: {context: ".",  dockerfile: "./Dockerfile-8.1"}
        restart: "no"
        env_file: [docker.env]
        working_dir: /var/code
        volumes:
            - "../composer.json:/var/code/composer.json"
            - "../phpunit.xml.dist:/var/code/phpunit.xml.dist"
            - "../src:/var/code/src"
            - "../tests:/var/code/tests"
            - "./composer.phar:/var/code/composer.phar"
            - "./run-internal.sh:/var/code/run-internal.sh"

    php82:
        image: php:8.1-cli
        depends_on: [postgres]
        build: {context: ".",  dockerfile: "./Dockerfile-8.2"}
        restart: "no"
        env_file: [docker.env]
        working_dir: /var/code
        volumes:
            - "../composer.json:/var/code/composer.json"
            - "../phpunit.xml.dist:/var/code/phpunit.xml.dist"
            - "../src:/var/code/src"
            - "../tests:/var/code/tests"
            - "./composer.phar:/var/code/composer.phar"
            - "./run-internal.sh:/var/code/run-internal.sh"
